services:
  frontend: 
    image: derekortiz/hc-frontend:latest
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
