export { ExpedienteActionButtons } from './ExpedienteActionButtons';
export { ExpedienteForm } from './ExpedienteForm';
export { HistorialMovimientosModal } from './HistorialMovimientosModal';
export { MovimientoValidationError } from './MovimientoValidationError';
export { EtiquetasAsignadas } from './EtiquetasAsignadas';
export { PhotoCircle } from './PhotoCircle';
export { AnimalDataFields } from './AnimalDataFields';
export { OtrosDatosSection } from './OtrosDatosSection';
export { MovimientoSection } from './MovimientoSection';
export { LugarDescripcionFields } from './LugarDescripcionFields';
export { FotoPackage } from './FotoPackage';
export { CapacidadAlertaBox } from './CapacidadAlertaBox';
export { FormularioBloqueadoCapacidad } from './FormularioBloqueadoCapacidad';
export type { Movimiento } from '@/schemas/movimiento.schema';
